---
layout: 11pt
header-includes:
  - \usepackage{lineno}
  - \usepackage{setspace}
  - \usepackage{todonotes}
  - \linespread{1.25}
  - \usepackage{rotating}
  - \usepackage{color, soul}
  - \usepackage[font={small},labelfont={bf},labelsep=quad]{caption}
  - \usepackage{tikz}
  - \usepackage{bm,mathrsfs}
  - \usepackage[sc]{mathpazo}
  - \usepackage{mathtools}
bibliography: ~/Dropbox/Bibliography/CoexistStability.bib
csl: components/ecology_letters.csl

## rmarkdown render options
output:
  pdf_document:
    fig_caption: true
    keep_tex: false
    number_sections: true
fontsize: 11pt
geometry: margin=1in
linkcolor: black
urlcolor: black
---

\renewcommand\linenumberfont{\normalfont\tiny\sffamily\color{gray}}
\renewcommand\thefigure{A1-\arabic{figure}}  
\renewcommand\thetable{A1-\arabic{table}}  
\renewcommand\thesection{Section A1.\arabic{section}}

\begin{center}
\textbf{\Large{Appendix 1}} \\
A.T. Tredennick, A.R. Kleinhesselink, B. Taylor \& P.B. Adler \\
``Consistent ecosystem functional response across precipitation extremes in a sagebrush steppe''  \\
\emph{PeerJ}
\end{center}

\linenumbers

\section{Estimating ANPP}
We used a radiometer to nondestructively estimate aboveground net primary productivity.
Our approach relies on relating greenness in a plot to aboveground biomass.
In each year we recorded ground reflectances at four bands, two associated with the red spectrum and two associated with the near-infrared spectrum (Table A1-1).
We took four readings per plot that were averaged for each band.
Bands 1 and 3 correspond to wavelengths collected by the MODIS satellite and bands 2 and 4 correspond to wavelengths collected by the AVHRR satellite.

| Band number | Spectrum name | Center wavelength | Corresponding satellite |
| ----------- | ------------- | ----------------- | ----------------------- |
| 1 | red | 626 nm | AVHRR |
| 2 | red | 652 nm | MODIS |
| 3 | near-infrared | 875 nm | AVHRR |
| 4 | near-infrared | 859 nm | MODIS |

Table: Radiometer specifications.

Using the RED and NIR reflectance values, we calculate the normalized difference vegetation index (NDVI) for each plot based on both AVHRR- and MODIS-based wavelengths.
We calculated NDVI as:
\vspace{-2em}
\begin{align}
\text{NDVI}_{\text{AVHRR}} &= \frac{b_3 - b_1}{b_3 + b_1} \\[10pt]
\text{NDVI}_{\text{MODIS}} &= \frac{b_4 - b_2}{b_4 + b_2}
\end{align}

\noindent{} where $b_x$ refers to band *x* (*x* = 1,2,3,4) in Table A1-1.

To convert plot NDVI to biomass, we regressed known biomass values from calibration plots against NDVI calculate for those plots.
Calibration plots were located near our experiment plots, and each year we located a new set of 10 plots in which we clipped all aboveground biomass, dried it to a constant weight at 60$^\circ$ C, and the weighed.
We used these biomass values to estimate regression parameters for both AVHRR- and MODIS-based NDVI.
We assessed model fit using $R^2$ and, for each year, we used the regression parameters associated with the best fit model to estimate biomass in the experimental plots based on their NDVI values (Table A1-2).
R code for this procedure is in the file "calibrate_radiometer_by_year.R" in the supplemental code set.

```{r ndvi_table, include=T, echo=F, comment=FALSE,warning=FALSE,message=FALSE,results='asis'}
library(xtable)
library(tidyverse)
library(dplyr)
tab_dat <- read.csv("../data/estimated_biomass/ndvi_biomass_regression_parameters.csv", row.names = 1) %>%
  filter(year > 2011 & year < 2017)
colnames(tab_dat) <- c("Year", "Intercept", "NDVI Slope", "$R^2$", "Min(biomass)", "Max(biomass)", "\\emph{N}", "Algorithm")

my_caption <- "Details of regression models used to estimate biomass each year."
print(xtable(tab_dat, caption = my_caption, digits = 2),
      caption.placement="top",
      include.rownames = F,
      sanitize.colnames.function = identity,
      comment = FALSE,
      size = "normalsize")
```





